### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by nkruglikov** [alexeykarnachev/the_shell#1]
(using gh issues as a social network comment section)

Nice! I am tinkering with aseprite + macroquad right now. How is your experience with raylib? And is it finished, or abandoned?

**Comment by alexeykarnachev** [comment]
Hi! It is absolutely not abandoned.
Great experience. All this opengl noise is factored out. But if you want, you have full access to the underlying opengl api.
For me raylib is finished, it provides everything you want for the low-level graphics stuff, but Ray (and some community guys) are still making releases and bug fixes

my tg if you need: https://t.me/kaktebyazvaly
